### ISSUE TITLE
fce defined vrací vždy true při použití selectoru

### ISSUE THREAD

**Issue by panther7** [seznam/teng#1]
data:
{"pokus":{"i":0}}

test:
<?teng frag pokus ?>
${defined(i)}
<?teng endfrag ?>
${defined($$pokus.i)}

výsledek:
0 1

**Comment by burlog** [comment]
The defined() function has strange/bad behaviour in more cases than this one. Its usage is not recommended and in the Teng3 the function become obsolete.
