### ISSUE TITLE
funkce `generatePage` nedobehne, v pripade chybneho regexu v sablone

### ISSUE THREAD

**Issue by tcpj** [seznam/teng#9]
`generatePage` nedobiha v pripade rekurzivniho regexu, asi by bylo dobre nejak limitovat generovani htmlka z sablony, casove nebo na konecny pocet volani.

function `generatePage` is getting hung on recursive regex, there should be a way to limit this recursion while generating html from template source, time or call limit
example:
```html
<p class="eta-url ellipsis"><a target="_top" href="${clickUrl}" class="url"><span>${regex_replace(unescape($clickthruUrl), "^(?:\\w+:\\/\\/)?(?:[^@\\/\\n]+@)?([\\w\\.-]+)?(.*)", "$1")}</span></a></p>
```

`clickthruUrl` nebyla vyplnena
`clickthruUrl` was not defined

**Comment by rembish** [comment]
Here you can see minimal source code, which completely freeze interpreter
```python
from teng import Teng
Teng().generatePage(templateString='${regex_replace("foo", "o?", "$1")}')
```

**Comment by Kak3n** [comment]
@burlog could you please take a look at this?

**Comment by fboranek** [comment]
Unfortunately, the problem is in `Pcre::replace` where is loop without any detection of recurrent replace. This snippet of code will not finish, using the latest `libpcre++-dev (0.9.5-6)`.  
```cpp
#include <pcre++.h>
#include <pcre.h>

int main() {
  std::string s{"$1"};
  std::string sRe{"o?"};
  std::string sText{"foo"};

  pcrepp::Pcre p(sRe, PCRE_GLOBAL | PCRE_UTF8);
  std::string sResult = p.replace(sText, s);
  std::cout << sResult << std::endl;
}
```

**Comment by burlog** [comment]
Yes, this is the core of the problem. The pcre++ is very light wrapper of libpcre and Teng uses only the replace feature from it. I will try tomorrow replace it with pcre++ with libpcre/std::regex/boost::regex implementation.

**Comment by burlog** [comment]
I have replaced the pcre++ with pcre2 and implemented teng owns replace function that fix this problem. Please can you verify it?

Thank you.

**Comment by fboranek** [comment]
We took all ours templates used for rendering ads and run synthetic test. There is no differences among results of `generate Page` for versions 2.3.24 and 2.3.32. It looks solid.

**Comment by burlog** [comment]
The issue seems to be fixed.
